lesson_4: Написал тесты для контроллеров
DrawGun/th_ror pull request #3
Opened 2017-10-14 21:15 UTC by DrawGun

2017-10-15 09:11 UTC, vkurennov requested changes

2017-10-15 09:11 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:body, :question_id)
qestion_id не должен в форме передавться, он уже в url передается. Надо по нему загрузить вопрос и связать его с ответом в create, а тут его нужно убрать

2017-10-15 09:11 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      let!(:answer_options) { {answer: attributes_for(:answer, question_id: question.id), question_id: question.id} }
question_id должен передаваться только один раз в параметрах, и не в атрибутах ответа

2017-10-15 09:11 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        }.to change(Answer, :count).by(1)
Тут надо проверить, что ответ связывается с вопросом.

2017-10-15 09:11 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        {answer: attributes_for(:invalid_answer, question_id: question.id), question_id: question.id}
question_id передаем только один раз

2017-10-15 10:26 UTC, DrawGun commented on spec/controllers/answers_controller_spec.rb
> +        }.to change(Answer, :count).by(1)
я написал об этом тест ниже
```
     it 'saved answer belongs_to question' do
        post :create, params: answer_options
        expect(assigns(:answer).question).to eq question
      end
```

2017-10-16 09:05 UTC, vkurennov approved these changes

2017-10-16 09:05 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:body).merge(question: @question)
Не нужно в strong params ничего добавлять, они не для этого предназначены. Это нужно делать в экшене и через ассоциации: `@question.answers.new(...)`

2017-10-18 20:26 UTC, merged