Lesson 5
DrawGun/th_ror pull request #4
Opened 2017-10-26 13:36 UTC by DrawGun

Написал тесты по задаче, реализовал базовые view.

2017-10-26 16:52 UTC, vkurennov requested changes

2017-10-26 16:52 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer = @question.answers.new(answer_params)
А как же ответ связывается с пользователем? Автор-то откуда возьмется?

2017-10-26 16:52 UTC, vkurennov commented on app/controllers/answers_controller.rb
>      redirect_to question_path(@question)
Нельзя делать редирект, если объект невалидный. Только рендер той страницы, где форма, т.е. страницы вопроса. Иначе, пропадет и то, что ввел пользователь и сами ошибки валидации

2017-10-26 16:52 UTC, vkurennov commented on app/controllers/questions_controller.rb
>      @question = Question.new(question_params)
И опять вопрос без автора.

2017-10-26 16:52 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer.destroy
Тут нужно проверять на автора, у нас по заданию нельзя удалить чужой ответ. И даже если в видах такая проверка есть (правда, непонятно как она работает, если у тебя ответы без автора создаются), то этого недостаточно: виды легко обойти и отправить запрос напрямую

2017-10-26 16:52 UTC, vkurennov commented on app/controllers/questions_controller.rb
>      @question.destroy
Тут нужна проверка на автора

2017-10-26 16:52 UTC, vkurennov commented on app/views/questions/new.html.slim
> += form_for @question do |f|
Нужен вывод ошибко валидации

2017-10-26 16:52 UTC, vkurennov commented on app/views/questions/show.html.slim
> +            = link_to I18n.t('.answers.delete_answer_button'), question_answer_path(@question, answer), method: :delete
Т.е. любой юзер (даже не залогиненный) может удалить любой ответ? У нас в задани это сформулировано иначе

2017-10-26 16:52 UTC, vkurennov commented on app/views/questions/show.html.slim
> +    = form_for :answer, url: question_answers_path(@question) do |f|
Нужен вывод ошибок валидации

2017-10-26 16:52 UTC, vkurennov commented on spec/acceptance/answers/create_spec.rb
> +    expect(page).to have_content I18n.t('.answers.confirmations.confirmed')
Надо проверить, что ответ есть на странице.

2017-10-26 16:52 UTC, vkurennov commented on spec/acceptance/answers/create_spec.rb
> +feature 'Create Question answers', %q{
Нужен сценарий на невалидный ответ - проверить, что выводятся ошибки валидации

2017-10-26 16:52 UTC, vkurennov commented on app/views/questions/show.html.slim
> +        = link_to I18n.t('.questions.delete_question_button'),  question_path(@question), method: :delete, class: 'btn btn-danger'
кто угодно может удалять вопросы?

2017-10-26 16:52 UTC, vkurennov commented on app/views/questions/show.html.slim
> +                  = link_to I18n.t('.answers.delete_answer_button'), question_answer_path(@question, answer), method: :delete, class: 'btn btn-danger btn-sm'
И ответы тоже может удалять хоть кто, даже не залогиненный юзер. А должен только **автор**

2017-10-26 16:52 UTC, vkurennov commented on spec/acceptance/questions/create_spec.rb
> +    expect(page).to have_content I18n.t('.questions.confirmations.confirmed')
Надо проверить, что заголовок и  тело вопроса появились на странице.

2017-10-26 16:52 UTC, vkurennov commented on spec/acceptance/questions/create_spec.rb
> +feature 'Create Question', %q{
Нужен сценарий на невалидный вопрос - проверить, что выводятся ошибки валидации

2017-10-26 16:52 UTC, vkurennov commented on spec/acceptance/answers/delete_spec.rb
> +  scenario 'Authenticated user creates question' do
У тебя явно название сценария не верное.

2017-10-26 16:52 UTC, vkurennov commented on spec/acceptance/answers/delete_spec.rb
> +    expect(page).to have_content I18n.t('.answers.confirmations.deleted')
Надо проверить, что ответа нет на странице

2017-10-26 16:52 UTC, vkurennov commented on spec/acceptance/answers/delete_spec.rb
> +feature 'Delete answer', %q{
У нас только автор может удалять ответ. Поэтому нужны сценарии для автора, для не-автора (залогинен другой юзер) и для гостя (незалогиненный юзер)

2017-10-26 16:52 UTC, vkurennov commented on spec/acceptance/answers/delete_spec.rb
> +    click_on I18n.t('.questions.delete_question_button')
Почему в удалении **ответа** клик идет по ссылке удаления **вопроса**?

2017-10-26 16:52 UTC, vkurennov commented on spec/acceptance/questions/delete_spec.rb
> +feature 'Delete Question', %q{
У нас только автор может удалять вопрос. Поэтому нужны сценарии для автора, для не-автора (залогинен другой юзер) и для гостя (незалогиненный юзер)

2017-10-26 16:52 UTC, vkurennov commented on spec/acceptance/questions/delete_spec.rb
> +    expect(page).to have_content I18n.t('.questions.confirmations.deleted')
Нужно проверить, что вопроса больше нет на странице

2017-10-26 16:52 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>      context 'with valid attributes' do
Тут нужно проверить, что ответ связывается с залогиненным юзером и вопросом

2017-10-26 16:52 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +  describe 'DELETE #destroy' do
Тут должно быть 2 контекста: для автора  и для не-автора.

2017-10-26 16:52 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    context 'as authtorized user' do
У нас не любой авторизированный юзер может удалить ответ. Только тот, кто его создал, т.е. автор. Если ты создал ответ, я не могу его удалить, даже если я залогинен.

2017-10-26 16:52 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>          expect { post(:create, params: {question: attributes_for(:question)}) }.to change(Question, :count).by(1)
тут надо проверить, что вопрос связывается с залогиненным юзером

2017-10-26 16:52 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
тут должно быть 2 контекста: для автора и для не-автора

2017-10-26 17:49 UTC, DrawGun commented on app/controllers/answers_controller.rb
> +    @answer = @question.answers.new(answer_params)
поправил

2017-10-26 17:49 UTC, DrawGun commented on app/controllers/answers_controller.rb
>      redirect_to question_path(@question)
поправил

2017-10-26 17:50 UTC, DrawGun commented on app/controllers/answers_controller.rb
> +    @answer.destroy
поправил

2017-10-26 17:50 UTC, DrawGun commented on app/controllers/questions_controller.rb
>      @question = Question.new(question_params)
поправил

2017-10-26 17:53 UTC, DrawGun commented on app/controllers/questions_controller.rb
>      @question.destroy
поправил

2017-10-26 17:53 UTC, DrawGun commented on app/views/questions/new.html.slim
> += form_for @question do |f|
поправил

2017-10-26 17:54 UTC, DrawGun commented on app/views/questions/show.html.slim
> +    = form_for :answer, url: question_answers_path(@question) do |f|
поправил

2017-10-26 17:56 UTC, DrawGun commented on app/views/questions/show.html.slim
> +        = link_to I18n.t('.questions.delete_question_button'),  question_path(@question), method: :delete, class: 'btn btn-danger'
поправил

2017-10-26 17:56 UTC, DrawGun commented on app/views/questions/show.html.slim
> +            = link_to I18n.t('.answers.delete_answer_button'), question_answer_path(@question, answer), method: :delete
поправил

2017-10-26 17:58 UTC, DrawGun commented on app/views/questions/show.html.slim
> +                  = link_to I18n.t('.answers.delete_answer_button'), question_answer_path(@question, answer), method: :delete, class: 'btn btn-danger btn-sm'
поправил

2017-10-26 20:49 UTC, DrawGun commented on spec/acceptance/answers/create_spec.rb
> +feature 'Create Question answers', %q{
поправил

2017-10-26 20:50 UTC, DrawGun commented on spec/acceptance/answers/create_spec.rb
> +    expect(page).to have_content I18n.t('.answers.confirmations.confirmed')
поправил

2017-10-26 21:00 UTC, DrawGun commented on spec/acceptance/answers/delete_spec.rb
> +feature 'Delete answer', %q{
поправил

2017-10-26 21:00 UTC, DrawGun commented on spec/acceptance/answers/delete_spec.rb
> +  scenario 'Authenticated user creates question' do
поправил

2017-10-26 21:01 UTC, DrawGun commented on spec/acceptance/answers/delete_spec.rb
> +    expect(page).to have_content I18n.t('.answers.confirmations.deleted')
поправил

2017-10-26 21:11 UTC, DrawGun commented on spec/acceptance/answers/delete_spec.rb
> +    click_on I18n.t('.questions.delete_question_button')
поправил

2017-10-26 21:21 UTC, DrawGun commented on spec/acceptance/questions/create_spec.rb
> +feature 'Create Question', %q{
поправил

2017-10-26 21:21 UTC, DrawGun commented on spec/acceptance/questions/create_spec.rb
> +    expect(page).to have_content I18n.t('.questions.confirmations.confirmed')
поправил

2017-10-26 21:25 UTC, DrawGun commented on spec/acceptance/questions/delete_spec.rb
> +feature 'Delete Question', %q{
поправил

2017-10-26 21:25 UTC, DrawGun commented on spec/acceptance/questions/delete_spec.rb
> +    expect(page).to have_content I18n.t('.questions.confirmations.deleted')
поправил

2017-10-26 21:28 UTC, DrawGun commented on spec/controllers/answers_controller_spec.rb
>      context 'with valid attributes' do
поправил

2017-10-26 21:30 UTC, DrawGun commented on spec/controllers/answers_controller_spec.rb
> +  describe 'DELETE #destroy' do
поправил

2017-10-26 21:30 UTC, DrawGun commented on spec/controllers/answers_controller_spec.rb
> +    context 'as authtorized user' do
поправил

2017-10-26 21:52 UTC, DrawGun commented on spec/controllers/questions_controller_spec.rb
>          expect { post(:create, params: {question: attributes_for(:question)}) }.to change(Question, :count).by(1)
поправил

2017-10-26 21:57 UTC, DrawGun commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
поправил

2017-10-27 08:40 UTC, vkurennov requested changes

2017-10-27 08:40 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer = @question.answers.new(answer_params.merge(user: current_user, question: @question))
А зачем еще раз мержить question? Ты же и так создаешь ответ через ассоциации вопроса.

2017-10-27 08:40 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user == @answer.user
* 1. Лучше проверять по user_id, чтобы не грузить ассоциацию из базы, она ведь не нужна.
* 2. Т.к. такая проверка будет встречаться часто, то лучше ее вынести в метод `User#author_of?`

2017-10-27 08:40 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question = Question.new(question_params.merge(user: current_user))
Здесь ни к чему merge, лучше через ассоциации current_user это сделать

2017-10-27 08:40 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if current_user == @question.user
Замени проверку на вызов `User#author_of?`

2017-10-27 08:40 UTC, vkurennov commented on app/views/questions/new.html.slim
> +  - @question.errors.full_messages.each do |msg|
Тут хорошо бы в начале условие поставить: `if @question.errors.any?`  и если ошибки есть, то выводить их

2017-10-27 08:40 UTC, vkurennov commented on app/views/questions/show.html.slim
> +      - if @question.user == current_user
Замени проверку на вызов `User#author_of?`

2017-10-27 08:40 UTC, vkurennov commented on app/views/questions/show.html.slim
> +            - if answer.id.present?
Лучше так:  `answer.persisted?`

2017-10-27 08:40 UTC, vkurennov commented on app/views/questions/show.html.slim
> +                  - if answer.user == current_user
Замени проверку на вызов `User#author_of?`

2017-10-27 08:40 UTC, vkurennov commented on app/views/questions/show.html.slim
> +        = form_for @answer, url: question_answers_path(@question) do |f|
для вложенных ресурсов не надо задавать url, надо передавать массив объектов:

`form_for [@question, @answer]`

2017-10-27 09:25 UTC, DrawGun commented on app/controllers/answers_controller.rb
> +    @answer = @question.answers.new(answer_params.merge(user: current_user, question: @question))
точно, когда я это писал, это казалось крутой идеей )

2017-10-27 09:27 UTC, DrawGun commented on app/controllers/questions_controller.rb
> +    @question = Question.new(question_params.merge(user: current_user))
поправил.

2017-10-27 09:32 UTC, DrawGun commented on app/controllers/answers_controller.rb
> +    if current_user == @answer.user
поправил

2017-10-27 09:35 UTC, DrawGun commented on app/controllers/questions_controller.rb
> +    if current_user == @question.user
поправил

2017-10-27 09:36 UTC, DrawGun commented on app/views/questions/new.html.slim
> +  - @question.errors.full_messages.each do |msg|
поправил, но думал, что там по-дефолту пустой массив

2017-10-27 09:37 UTC, DrawGun commented on app/views/questions/new.html.slim
> +  - @question.errors.full_messages.each do |msg|
в show, для валидации ошибок `answer` тоже поправил

2017-10-27 09:37 UTC, DrawGun commented on app/views/questions/show.html.slim
> +      - if @question.user == current_user
поправил

2017-10-27 09:40 UTC, DrawGun commented on app/views/questions/show.html.slim
> +            - if answer.id.present?
точно, так реально красивей )

2017-10-27 09:41 UTC, DrawGun commented on app/views/questions/show.html.slim
> +                  - if answer.user == current_user
поправил

2017-10-27 09:42 UTC, DrawGun commented on app/views/questions/show.html.slim
> +        = form_for @answer, url: question_answers_path(@question) do |f|
поправил.
мне всегда казалось, что это дело вкуса, я ошибаюсь? есть ли какая-то выгода использовать этот способ кроме красоты? реально очень интересно узнать

2017-10-27 09:45 UTC, DrawGun commented
@vkurennov попраил, есть пара вопросов

- почему все-таки делать `merge` в `strong_params` это не круто, если это, особенно внутренние поля, типа `current_user`? Я помню Ваш пример, где это юзалось на уровень выше, но это фактически тоже самое. Хочется понять в чем причина и как правильней

- можете подсказать где хранятся локали всяких ошибок и успехов active_record?

2017-10-27 09:50 UTC, DrawGun commented
![img](https://user-images.githubusercontent.com/4161357/32098424-55927ff2-bb15-11e7-96fb-4898fbc8e87f.png)

2017-10-27 15:29 UTC, vkurennov commented on app/views/questions/show.html.slim
> +        = form_for @answer, url: question_answers_path(@question) do |f|
Нет, по сути, это просто принятый способ записи вложенных ресурсов. Он короче и рекомендуется как дефолтный

2017-10-27 15:35 UTC, vkurennov commented
> почему все-таки делать merge в strong_params это не круто, если это, особенно внутренние поля, типа current_user? Я помню Ваш пример, где это юзалось на уровень выше, но это фактически тоже самое. Хочется понять в чем причина и как правильней

Причина в принципе single responsibility, т.е. единой ответсвенности. Каждый класс и метод должен делать одну, четко обозначенную вещь. В случае strong params - это предоставление белого списка полей, которые приходят из формы. В его ответсвенность не должно входить добавление других полей. Т.е. это неверно именно с т.з. того, что нарушает этот важный принцип проектирования, что ведет к плохому коду.

> можете подсказать где хранятся локали всяких ошибок и успехов active_record?

Вот тут все подробно описано: http://guides.rubyonrails.org/i18n.html#translations-for-active-record-models

2017-10-27 15:35 UTC, vkurennov approved these changes

2017-10-27 15:35 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user.author_of?(@answer.user_id)
Не надо передавть id, надо передавать  сам объект @answer, а в методе уже получать у него user_id. Иначе получается, как будто мы справшивае, явлеяется ли юзер автором данного user_id. А спрашивать надо про ответ

2017-10-27 15:35 UTC, vkurennov commented on spec/models/user_spec.rb
> +describe User do
А где же тесты на метод `author_of?`

2017-10-27 15:35 UTC, vkurennov commented on app/models/user.rb
> +  def author_of?(user_id)
Метод должен принимать объект, а не user_id

2017-10-29 16:51 UTC, merged