Lesson 7
DrawGun/th_ror pull request #6
Opened 2017-11-13 22:21 UTC by DrawGun

2017-11-13 22:27 UTC, DrawGun commented on spec/acceptance/questions/edit_spec.rb
> +      # scenario 'with valid attrs' do
Вот этот тест не проходит, хотя логика вся абсолютно одинаковая. Не пойму почему не работает. Возможно, я что-то делаю не так )
Предположений два:

- не дожидаюсь `ajax`, хотя, пробовал делать `sleep 5` и все равно не проходит

- я использую 4 версию bootstrap и там класс `.d_none` который я использую прописан, как 
```display: none !important;```
и скриптами не перебивается, поэтому я его просто удаляю и добавляю, возможно проблема в этом

2017-11-14 13:13 UTC, vkurennov requested changes

2017-11-14 13:13 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user.author_of?(@answer) && @question.update(best_answer_id: @answer.id)
Плохая архитектура решения лучшего ответа. У тебя получается, что вопрос является родительским элементом ко всем вопросам, и при этом дочерним к лучшему (одновременно являясь для него же родителем). Связи запутаны, такое решение будет сложно поддерживать в последствии. Гораздо лушче сделать атрибут (флаг) у ответа, тогда связи остаются прежними, но нужно будет сделать метод, который перед установкой флага сбрасывает флаг у существующего лучшего ответа.

2017-11-14 13:13 UTC, vkurennov commented on app/models/question.rb
> +  def best_answer?(answer)
Если будет флаг, то такой метод будет не нужен, т.к. флаг и будет возвращать результат

2017-11-15 09:46 UTC, palkan-th commented on spec/acceptance/questions/edit_spec.rb
> +      # scenario 'with valid attrs' do
А что именно не проходит? Где падает?

2017-11-15 09:49 UTC, DrawGun commented on spec/acceptance/questions/edit_spec.rb
> +      # scenario 'with valid attrs' do
@palkan-th не проходит ни один из `expect`

2017-11-15 09:58 UTC, DrawGun commented on spec/acceptance/questions/edit_spec.rb
> +      # scenario 'with valid attrs' do
@palkan-th сорри, после рефакторинга ошибка стала вполне ясной, неправильно указал  селектор для `within` блока.

2017-11-15 09:58 UTC, palkan-th commented on spec/acceptance/questions/edit_spec.rb
> +      scenario 'with valid attrs' do
Давай так сделаем: `scenario 'with valid attrs', :aggregate_failures do`

Чтобы все expect проверить как раз. Скопируй сюда вывод просто.

2017-11-15 10:03 UTC, DrawGun commented on spec/acceptance/questions/edit_spec.rb
> +      scenario 'with valid attrs' do
как я понял падал вот этот
`expect(page).to_not have_selector 'textarea'`
так как в прошлой реализации была не одна `textarea`

щас поправил селектор на более точный, который захватывает только область с редактированием и тест прошел

2017-11-15 11:18 UTC, vkurennov requested changes

2017-11-15 11:18 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user.author_of?(@answer) && @answer.update(best: @answer.id)
Почему у тебя в поле best хранится id ответа, причем того же самого, у которого ты апдейтишь это поле? Зачем объекту значение своего же id? Это дублирование данных.  best - это флаг, т.е. поле типа boolean.
Далее, не достаточно просто обновить этот флаг. нужно сначала снять флаг со старого лучшего ответа, если он есть. А т.к. тут 2 апдейта, то уже нужна [транзакция](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html). А это уже сложная бизнес-логика и ее надо вынести в модель

2017-11-15 11:18 UTC, vkurennov commented on app/models/answer.rb
> +  before_save :reset_best, if: 'best_changed? && best'
Ты разнес эти действия на 2 разных класса, во-первых, сама логика действия разорвана, что плохо, потому что действия должны быть одновременные, во-вторых, так нельзя применить транзакцию

2017-11-15 11:18 UTC, vkurennov commented on db/migrate/20171114173653_add_best_attr_to_answer.rb
> +    add_column :answers, :best, :boolean, null: false, default: false
У тебя же верный флаг, так зачем в него писать id вместо true в контроллере?

2017-11-15 11:34 UTC, DrawGun commented on db/migrate/20171114173653_add_best_attr_to_answer.rb
> +    add_column :answers, :best, :boolean, null: false, default: false
это опечатка, просто перенес старый код, поправлю

2017-11-15 11:41 UTC, DrawGun commented on app/controllers/answers_controller.rb
> +    if current_user.author_of?(@answer) && @answer.update(best: @answer.id)
точно, опечатка, поправил

2017-11-15 11:41 UTC, DrawGun commented on app/models/answer.rb
> +  before_save :reset_best, if: 'best_changed? && best'
не понял в чем и почему проблема и что требуется, можно чуть больше пояснений?

2017-11-15 12:28 UTC, DrawGun commented on app/models/answer.rb
> +  before_save :reset_best, if: 'best_changed? && best'
я о том, что вызывать метод `set_as_best` на `answer` не панацея, так как если мы скажем из консоли поменяем флаг для другого ответа, то их станет два.
я не отрицаю, что моя реализация не до конца верная, прошу помощи у ментора

2017-11-17 09:12 UTC, vkurennov commented on app/models/answer.rb
> +  before_save :reset_best, if: 'best_changed? && best'
Да, конечно, такая возможность - установить из консоли флаг - остается. Но мы не даем пользователю доступ к консоли. У него есть один способ это сделать - через контроллер, в котором будет вызываться метод. В своем коде мы должны контроллировать, что установка флага происходит через метод.

2017-11-17 09:15 UTC, vkurennov requested changes

2017-11-17 09:15 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user.author_of?(@answer) && @answer.update(best: true)
У тебя по сути, как все было, так и осталось. По-прежнему, просиходят 2 апдейта в 2-х разных местах. Нужно же сделать метод set_best в модели Answer, который сделает сразу эти 2 апдейта, при этом, обернув их в [транзакцию](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html).

2017-11-17 13:49 UTC, vkurennov approved these changes

2017-11-17 13:49 UTC, vkurennov commented on app/models/answer.rb
> +      self.update(best: true)
Транзакция откатывается только в случае исключения, поэтому тут должен быть `update!`

2017-11-17 13:49 UTC, vkurennov commented on spec/models/answer_spec.rb
> +    expect(answer2.reload.best).to be false
Тут нужно несколько тестов, в юнит-тестах действует правило: один тест - один expect.

2017-11-17 14:17 UTC, merged