Lesson 9
DrawGun/th_ror pull request #8
Opened 2017-12-07 23:56 UTC by DrawGun

2017-12-08 00:02 UTC, DrawGun commented on spec/acceptance/answers/vote_answer_spec.rb
> +        expect(find('.vote-count').value).to eq '1'
вот тут все равно 0
дебаггер показывает, что в базе нет данных а иногда показывает, что они есть

2017-12-08 00:02 UTC, DrawGun commented on spec/acceptance/questions/vote_question_spec.rb
> +        expect(find('.vote-count').value).to eq '1'
аналогично тут. вижу, что в код контроллеров прохожу и дохожу до строчки рендеринга json
может проблема в этом?

2017-12-08 09:16 UTC, DrawGun commented on spec/acceptance/answers/vote_answer_spec.rb
> +        expect(find('.vote-count').value).to eq '1'
тут подумал, что возможно, проблема в том, что не отрабатывают скрипты, по какой причине не особо понятно

2017-12-09 10:53 UTC, vkurennov requested changes

2017-12-09 10:53 UTC, vkurennov commented on config/routes.rb
> +    resources :answers, concerns: :votable do
Пора объявить ресурс answers как shallow, тогда не придется передавать вопрос там, где достаточно только ответа.

2017-12-09 10:53 UTC, vkurennov commented on app/assets/javascripts/votes.coffee
> +    else if response.type == 'Answer'
Если формирование селектора для вопроса и ответов сделать по одному принципу, то можно будет избавиться от условия и динамически формировать селектор на основе приходящих данных

2017-12-09 10:53 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +    @votable = if params[:controller] == 'questions'
Если применить немного методов манипулации над строками (перевод в  CamelCase) и чуток матпрограммирования (получение из строки класса), то условие будет не нужно, т.к. можно будет динамически, на основе параметров определять контроллер и и по нему класс модели.
И тогда консерн станет универсальным. И если завтра мы захотим добавить его к комментариям, то все будет работать без изменения самого консерна

2017-12-14 08:52 UTC, vkurennov approved these changes

2017-12-14 08:52 UTC, vkurennov commented on app/assets/javascripts/votes.coffee
> +    votable = $("#{response.selector}")
Передавать селектор в json - так себе идея. Достаточно тип и id было передавать, а уже на клиенте из этого собирать селектор

2017-12-14 08:52 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +    puts "@votable.evaluation -> #{@votable.evaluation}"
Это точно нужно?

2017-12-15 17:06 UTC, merged